# Generated by Django 2.2.12 on 2020-04-04 22:49

import api.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='default_username', max_length=50, unique=True)),
                ('chats', djongo.models.fields.ArrayField(model_container=api.models.Chat, unique=True)),
            ],
        ),
    ]
